version: '3.8'

services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    networks:
      - network1
    volumes:
      - ./gateway-service:/app
    environment:
      - NODE_ENV=${NODE_ENV}

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    networks:
      - network1
    volumes:
      - ./notification-service:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - gateway-service

  db:
    build:
      context: ./user-service
      dockerfile: Dockerfile.db
    networks:
      - network1
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - network1
    environment:
      DB_NAME: ${PG_DATABASE}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASSWORD}
      DB_HOST: db
      DB_PORT: ${PG_PORT}
    depends_on:
      - db
      - gateway-service

networks:
  network1:
    driver: bridge
