version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_DB: $PG_NAME 

  user-service:
    build: 
      context: .
    environment:
      PG_NAME: $PG_NAME 
      PG_USER: $PG_USER
      PG_PASS: $PG_PASS
      PG_HOST: db
    depends_on:
      - db