version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    networks:
      - network1
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  user-service:
    build: 
      context: .
    networks:
      - network1
    environment:
      DB_NAME: ${PG_DATABASE}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASSWORD}
      DB_HOST: db
      DB_PORT: ${PG_PORT}
    depends_on:
      - db
        # condition: service_healthy

networks:
  network1:
    driver: bridge
