version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - network1
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  user-service:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - network1
    environment:
      DB_NAME: ${PG_DATABASE}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASSWORD}
      DB_HOST: db
      DB_PORT: ${PG_PORT}
  
  user-service-test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    networks:
      - network1
    environment:
      DB_NAME: ${PG_DATABASE}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASSWORD}
      DB_HOST: db
      DB_PORT: ${PG_PORT}
    depends_on:
      - db
      - user-service

networks:
  network1:
    driver: bridge
