services:

  db:
    build:
      context: ./user-service
      dockerfile: Dockerfile.db

  user-service:
    build: 
      context: ./user-service
    environment:
      DB_NAME: $DB_NAME 
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: db
    depends_on:
      - db