version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME 

  user-service:
    build: 
      context: .
    environment:
      DB_NAME: $DB_NAME 
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: db
    depends_on:
      - db