name: CI/CD Pipeline

on:
  push:
    branches:
      - ci-setup

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up .env.test
        run: |
          cp user-service/.env.test user-service/.env && echo "Copied user-serivce .env.test file"
          cp notification-service/.env.test notification-service/.env && echo "Copied notification-serivce .env.test file"
          cp gateway-service/.env.test gateway-service/.env && echo "Copied gateway-serivce .env.test file"

      - name: Build and Test
        run: docker-compose up #--build --abort-on-container-exit

      # - name: Run tests
      #   run: docker-compose run -e NODE_ENV=test user-service

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for user-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/open-chat-user-app:${{ github.sha }} ./user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/open-chat-user-app:${{ github.sha }}

      - name: Build and push Docker image for notification-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/open-chat-notification-app:${{ github.sha }} ./notification-service
          docker push ${{ secrets.DOCKER_USERNAME }}/open-chat-notification-app:${{ github.sha }}

      - name: Build and push Docker image for gateway-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/open-chat-gateway-app:${{ github.sha }} ./gateway-service
          docker push ${{ secrets.DOCKER_USERNAME }}/open-chat-gateway-app:${{ github.sha }}
